version: '3'

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/universal:linux
    volumes:
      - ..:/workspace:cached

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data:
