version: '3'

services:
  devcontainer:
    image: mcr.microsoft.com/vscode/devcontainers/universal:1.0
    user: vscode
    environment:
      MYSQL_HOST: mysql
    volumes:
      - ..:/workspace:cached
      
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
